name: pokedex_5e_ita
description: "Trainer Atlas, companion non ufficiale in italiano per campagne con creature tascabili in 5e."
publish_to: 'none'

version: 1.3.0+6

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  scrollable_positioned_list: ^0.3.8
  file_picker: ^10.3.10
  share_plus: ^12.0.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/data/
    - assets/data/pokemon/
    - assets/data/moves/
    - assets/data_webapp/
    - assets/textures/gui/
    - assets/textures/gui/border/
    - assets/textures/gui/btn/
    - assets/textures/gui/icon/
    - assets/textures/gui/status/
    - assets/textures/pokemons/
    - assets/textures/sprites/
    - assets/textures/trainers/
    - assets/textures/type_names/
    - assets/textures/textures_webapp/items/
    - assets/textures/textures_webapp/pokemon/
    - assets/textures/textures_webapp/pokemon_transforms/
    - assets/textures/textures_webapp/pokemon/aegislash-shield/
    - assets/textures/textures_webapp/pokemon/cherrim-sunshine/
    - assets/textures/textures_webapp/pokemon/cramorant-gorging/
    - assets/textures/textures_webapp/pokemon/cramorant-gulping/
    - assets/textures/textures_webapp/pokemon/darmanitan-galar-standard/
    - assets/textures/textures_webapp/pokemon/darmanitan-galar-zen/
    - assets/textures/textures_webapp/pokemon/darmanitan-zen/
    - assets/textures/textures_webapp/pokemon/eiscue-noice-face/
    - assets/textures/textures_webapp/pokemon/mimikyu-busted/
    - assets/textures/textures_webapp/pokemon/morpeko-hangry/
    - assets/textures/textures_webapp/pokemon/palafin-hero/
    - assets/textures/textures_webapp/pokemon/abomasnow/
    - assets/textures/textures_webapp/pokemon/abra/
    - assets/textures/textures_webapp/pokemon/absol/
    - assets/textures/textures_webapp/pokemon/accelgor/
    - assets/textures/textures_webapp/pokemon/aegislash/
    - assets/textures/textures_webapp/pokemon/aerodactyl/
    - assets/textures/textures_webapp/pokemon/aggron/
    - assets/textures/textures_webapp/pokemon/aipom/
    - assets/textures/textures_webapp/pokemon/alakazam/
    - assets/textures/textures_webapp/pokemon/alcremie/
    - assets/textures/textures_webapp/pokemon/alolan-diglett/
    - assets/textures/textures_webapp/pokemon/alolan-dugtrio/
    - assets/textures/textures_webapp/pokemon/alolan-exeggutor/
    - assets/textures/textures_webapp/pokemon/alolan-geodude/
    - assets/textures/textures_webapp/pokemon/alolan-golem/
    - assets/textures/textures_webapp/pokemon/alolan-graveler/
    - assets/textures/textures_webapp/pokemon/alolan-grimer/
    - assets/textures/textures_webapp/pokemon/alolan-marowak/
    - assets/textures/textures_webapp/pokemon/alolan-meowth/
    - assets/textures/textures_webapp/pokemon/alolan-muk/
    - assets/textures/textures_webapp/pokemon/alolan-ninetales/
    - assets/textures/textures_webapp/pokemon/alolan-persian/
    - assets/textures/textures_webapp/pokemon/alolan-raichu/
    - assets/textures/textures_webapp/pokemon/alolan-raticate/
    - assets/textures/textures_webapp/pokemon/alolan-rattata/
    - assets/textures/textures_webapp/pokemon/alolan-sandshrew/
    - assets/textures/textures_webapp/pokemon/alolan-sandslash/
    - assets/textures/textures_webapp/pokemon/alolan-vulpix/
    - assets/textures/textures_webapp/pokemon/alomomola/
    - assets/textures/textures_webapp/pokemon/altaria/
    - assets/textures/textures_webapp/pokemon/amaura/
    - assets/textures/textures_webapp/pokemon/ambipom/
    - assets/textures/textures_webapp/pokemon/amoonguss/
    - assets/textures/textures_webapp/pokemon/ampharos/
    - assets/textures/textures_webapp/pokemon/annihilape/
    - assets/textures/textures_webapp/pokemon/anorith/
    - assets/textures/textures_webapp/pokemon/appletun/
    - assets/textures/textures_webapp/pokemon/applin/
    - assets/textures/textures_webapp/pokemon/araquanid/
    - assets/textures/textures_webapp/pokemon/arbok/
    - assets/textures/textures_webapp/pokemon/arboliva/
    - assets/textures/textures_webapp/pokemon/arcanine/
    - assets/textures/textures_webapp/pokemon/arcanine-hisui/
    - assets/textures/textures_webapp/pokemon/arceus/
    - assets/textures/textures_webapp/pokemon/archaludon/
    - assets/textures/textures_webapp/pokemon/archen/
    - assets/textures/textures_webapp/pokemon/archeops/
    - assets/textures/textures_webapp/pokemon/arctibax/
    - assets/textures/textures_webapp/pokemon/arctovish/
    - assets/textures/textures_webapp/pokemon/arctozolt/
    - assets/textures/textures_webapp/pokemon/ariados/
    - assets/textures/textures_webapp/pokemon/armaldo/
    - assets/textures/textures_webapp/pokemon/armarouge/
    - assets/textures/textures_webapp/pokemon/aromatisse/
    - assets/textures/textures_webapp/pokemon/aron/
    - assets/textures/textures_webapp/pokemon/arrokuda/
    - assets/textures/textures_webapp/pokemon/articuno/
    - assets/textures/textures_webapp/pokemon/articuno-galar/
    - assets/textures/textures_webapp/pokemon/audino/
    - assets/textures/textures_webapp/pokemon/aurorus/
    - assets/textures/textures_webapp/pokemon/avalugg/
    - assets/textures/textures_webapp/pokemon/avalugg-hisui/
    - assets/textures/textures_webapp/pokemon/axew/
    - assets/textures/textures_webapp/pokemon/azelf/
    - assets/textures/textures_webapp/pokemon/azumarill/
    - assets/textures/textures_webapp/pokemon/azurill/
    - assets/textures/textures_webapp/pokemon/bagon/
    - assets/textures/textures_webapp/pokemon/baltoy/
    - assets/textures/textures_webapp/pokemon/banette/
    - assets/textures/textures_webapp/pokemon/barbaracle/
    - assets/textures/textures_webapp/pokemon/barboach/
    - assets/textures/textures_webapp/pokemon/barraskewda/
    - assets/textures/textures_webapp/pokemon/basculegion-f/
    - assets/textures/textures_webapp/pokemon/basculegion-m/
    - assets/textures/textures_webapp/pokemon/basculin/
    - assets/textures/textures_webapp/pokemon/basculin-blue-striped/
    - assets/textures/textures_webapp/pokemon/basculin-white-striped/
    - assets/textures/textures_webapp/pokemon/bastiodon/
    - assets/textures/textures_webapp/pokemon/baxcalibur/
    - assets/textures/textures_webapp/pokemon/bayleef/
    - assets/textures/textures_webapp/pokemon/beartic/
    - assets/textures/textures_webapp/pokemon/beautifly/
    - assets/textures/textures_webapp/pokemon/beedrill/
    - assets/textures/textures_webapp/pokemon/beheeyem/
    - assets/textures/textures_webapp/pokemon/beldum/
    - assets/textures/textures_webapp/pokemon/bellibolt/
    - assets/textures/textures_webapp/pokemon/bellossom/
    - assets/textures/textures_webapp/pokemon/bellsprout/
    - assets/textures/textures_webapp/pokemon/bergmite/
    - assets/textures/textures_webapp/pokemon/bewear/
    - assets/textures/textures_webapp/pokemon/bibarel/
    - assets/textures/textures_webapp/pokemon/bidoof/
    - assets/textures/textures_webapp/pokemon/binacle/
    - assets/textures/textures_webapp/pokemon/bisharp/
    - assets/textures/textures_webapp/pokemon/blacephalon/
    - assets/textures/textures_webapp/pokemon/black-kyurem/
    - assets/textures/textures_webapp/pokemon/blastoise/
    - assets/textures/textures_webapp/pokemon/blaziken/
    - assets/textures/textures_webapp/pokemon/blipbug/
    - assets/textures/textures_webapp/pokemon/blissey/
    - assets/textures/textures_webapp/pokemon/blitzle/
    - assets/textures/textures_webapp/pokemon/boldore/
    - assets/textures/textures_webapp/pokemon/boltund/
    - assets/textures/textures_webapp/pokemon/bombirdier/
    - assets/textures/textures_webapp/pokemon/bonsly/
    - assets/textures/textures_webapp/pokemon/bouffalant/
    - assets/textures/textures_webapp/pokemon/bounsweet/
    - assets/textures/textures_webapp/pokemon/braixen/
    - assets/textures/textures_webapp/pokemon/brambleghast/
    - assets/textures/textures_webapp/pokemon/bramblin/
    - assets/textures/textures_webapp/pokemon/braviary/
    - assets/textures/textures_webapp/pokemon/braviary-hisui/
    - assets/textures/textures_webapp/pokemon/breloom/
    - assets/textures/textures_webapp/pokemon/brionne/
    - assets/textures/textures_webapp/pokemon/bronzong/
    - assets/textures/textures_webapp/pokemon/bronzor/
    - assets/textures/textures_webapp/pokemon/brute-bonnet/
    - assets/textures/textures_webapp/pokemon/bruxish/
    - assets/textures/textures_webapp/pokemon/budew/
    - assets/textures/textures_webapp/pokemon/buizel/
    - assets/textures/textures_webapp/pokemon/bulbasaur/
    - assets/textures/textures_webapp/pokemon/buneary/
    - assets/textures/textures_webapp/pokemon/bunnelby/
    - assets/textures/textures_webapp/pokemon/burmy/
    - assets/textures/textures_webapp/pokemon/butterfree/
    - assets/textures/textures_webapp/pokemon/buzzwole/
    - assets/textures/textures_webapp/pokemon/cacnea/
    - assets/textures/textures_webapp/pokemon/cacturne/
    - assets/textures/textures_webapp/pokemon/calyrex/
    - assets/textures/textures_webapp/pokemon/calyrex-ice/
    - assets/textures/textures_webapp/pokemon/calyrex-shadow/
    - assets/textures/textures_webapp/pokemon/camerupt/
    - assets/textures/textures_webapp/pokemon/capsakid/
    - assets/textures/textures_webapp/pokemon/carbink/
    - assets/textures/textures_webapp/pokemon/carkol/
    - assets/textures/textures_webapp/pokemon/carnivine/
    - assets/textures/textures_webapp/pokemon/carracosta/
    - assets/textures/textures_webapp/pokemon/carvanha/
    - assets/textures/textures_webapp/pokemon/cascoon/
    - assets/textures/textures_webapp/pokemon/castform/
    - assets/textures/textures_webapp/pokemon/caterpie/
    - assets/textures/textures_webapp/pokemon/celebi/
    - assets/textures/textures_webapp/pokemon/celesteela/
    - assets/textures/textures_webapp/pokemon/centiskorch/
    - assets/textures/textures_webapp/pokemon/ceruledge/
    - assets/textures/textures_webapp/pokemon/cetitan/
    - assets/textures/textures_webapp/pokemon/cetoddle/
    - assets/textures/textures_webapp/pokemon/chandelure/
    - assets/textures/textures_webapp/pokemon/chansey/
    - assets/textures/textures_webapp/pokemon/charcadet/
    - assets/textures/textures_webapp/pokemon/charizard/
    - assets/textures/textures_webapp/pokemon/charjabug/
    - assets/textures/textures_webapp/pokemon/charmander/
    - assets/textures/textures_webapp/pokemon/charmeleon/
    - assets/textures/textures_webapp/pokemon/chatot/
    - assets/textures/textures_webapp/pokemon/cherrim/
    - assets/textures/textures_webapp/pokemon/cherubi/
    - assets/textures/textures_webapp/pokemon/chesnaught/
    - assets/textures/textures_webapp/pokemon/chespin/
    - assets/textures/textures_webapp/pokemon/chewtle/
    - assets/textures/textures_webapp/pokemon/chi-yu/
    - assets/textures/textures_webapp/pokemon/chien-pao/
    - assets/textures/textures_webapp/pokemon/chikorita/
    - assets/textures/textures_webapp/pokemon/chimchar/
    - assets/textures/textures_webapp/pokemon/chimecho/
    - assets/textures/textures_webapp/pokemon/chinchou/
    - assets/textures/textures_webapp/pokemon/chingling/
    - assets/textures/textures_webapp/pokemon/cinccino/
    - assets/textures/textures_webapp/pokemon/cinderace/
    - assets/textures/textures_webapp/pokemon/clamperl/
    - assets/textures/textures_webapp/pokemon/clauncher/
    - assets/textures/textures_webapp/pokemon/clawitzer/
    - assets/textures/textures_webapp/pokemon/claydol/
    - assets/textures/textures_webapp/pokemon/clefable/
