name: pokedex_5e_ita
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  scrollable_positioned_list: ^0.3.8

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/data/
    - assets/data/pokemon/
    - assets/data/moves/
    - assets/data_webapp/
    - assets/textures/gui/
    - assets/textures/gui/border/
    - assets/textures/gui/btn/
    - assets/textures/gui/icon/
    - assets/textures/gui/status/
    - assets/textures/pokemons/
    - assets/textures/sprites/
    - assets/textures/trainers/
    - assets/textures/type_names/
    - assets/textures/textures_webapp/items/
    - assets/textures/textures_webapp/pokemon/
    - assets/textures/textures_webapp/pokemon_transforms/
    - assets/textures/textures_webapp/pokemon/grookey/
    - assets/textures/textures_webapp/pokemon/thwackey/
    - assets/textures/textures_webapp/pokemon/rillaboom/
    - assets/textures/textures_webapp/pokemon/scorbunny/
    - assets/textures/textures_webapp/pokemon/raboot/
    - assets/textures/textures_webapp/pokemon/cinderace/
    - assets/textures/textures_webapp/pokemon/sobble/
    - assets/textures/textures_webapp/pokemon/drizzile/
    - assets/textures/textures_webapp/pokemon/inteleon/
    - assets/textures/textures_webapp/pokemon/skwovet/
    - assets/textures/textures_webapp/pokemon/greedent/
    - assets/textures/textures_webapp/pokemon/rookidee/
    - assets/textures/textures_webapp/pokemon/corvisquire/
    - assets/textures/textures_webapp/pokemon/corviknight/
    - assets/textures/textures_webapp/pokemon/blipbug/
    - assets/textures/textures_webapp/pokemon/dottler/
    - assets/textures/textures_webapp/pokemon/orbeetle/
    - assets/textures/textures_webapp/pokemon/nickit/
    - assets/textures/textures_webapp/pokemon/thievul/
    - assets/textures/textures_webapp/pokemon/gossifleur/
    - assets/textures/textures_webapp/pokemon/eldegoss/
    - assets/textures/textures_webapp/pokemon/wooloo/
    - assets/textures/textures_webapp/pokemon/dubwool/
    - assets/textures/textures_webapp/pokemon/chewtle/
    - assets/textures/textures_webapp/pokemon/drednaw/
    - assets/textures/textures_webapp/pokemon/yamper/
    - assets/textures/textures_webapp/pokemon/boltund/
    - assets/textures/textures_webapp/pokemon/rolycoly/
    - assets/textures/textures_webapp/pokemon/carkol/
    - assets/textures/textures_webapp/pokemon/coalossal/
    - assets/textures/textures_webapp/pokemon/applin/
    - assets/textures/textures_webapp/pokemon/flapple/
    - assets/textures/textures_webapp/pokemon/appletun/
    - assets/textures/textures_webapp/pokemon/silicobra/
    - assets/textures/textures_webapp/pokemon/sandaconda/
    - assets/textures/textures_webapp/pokemon/cramorant/
    - assets/textures/textures_webapp/pokemon/arrokuda/
    - assets/textures/textures_webapp/pokemon/barraskewda/
    - assets/textures/textures_webapp/pokemon/toxel/
    - assets/textures/textures_webapp/pokemon/toxtricity/
    - assets/textures/textures_webapp/pokemon/sizzlipede/
    - assets/textures/textures_webapp/pokemon/centiskorch/
    - assets/textures/textures_webapp/pokemon/clobbopus/
    - assets/textures/textures_webapp/pokemon/grapploct/
    - assets/textures/textures_webapp/pokemon/sinistea/
    - assets/textures/textures_webapp/pokemon/polteageist/
    - assets/textures/textures_webapp/pokemon/hatenna/
    - assets/textures/textures_webapp/pokemon/hattrem/
    - assets/textures/textures_webapp/pokemon/hatterene/
    - assets/textures/textures_webapp/pokemon/impidimp/
    - assets/textures/textures_webapp/pokemon/morgrem/
    - assets/textures/textures_webapp/pokemon/grimmsnarl/
    - assets/textures/textures_webapp/pokemon/obstagoon/
    - assets/textures/textures_webapp/pokemon/perrserker/
    - assets/textures/textures_webapp/pokemon/cursola/
    - assets/textures/textures_webapp/pokemon/sirfetchd/
    - assets/textures/textures_webapp/pokemon/mr-rime/
    - assets/textures/textures_webapp/pokemon/runerigus/
    - assets/textures/textures_webapp/pokemon/milcery/
    - assets/textures/textures_webapp/pokemon/alcremie/
    - assets/textures/textures_webapp/pokemon/falinks/
    - assets/textures/textures_webapp/pokemon/pincurchin/
    - assets/textures/textures_webapp/pokemon/snom/
    - assets/textures/textures_webapp/pokemon/frosmoth/
    - assets/textures/textures_webapp/pokemon/stonjourner/
    - assets/textures/textures_webapp/pokemon/eiscue/
    - assets/textures/textures_webapp/pokemon/indeedee/
    - assets/textures/textures_webapp/pokemon/morpeko/
    - assets/textures/textures_webapp/pokemon/cufant/
    - assets/textures/textures_webapp/pokemon/copperajah/
    - assets/textures/textures_webapp/pokemon/dracozolt/
    - assets/textures/textures_webapp/pokemon/arctozolt/
    - assets/textures/textures_webapp/pokemon/dracovish/
    - assets/textures/textures_webapp/pokemon/arctovish/
    - assets/textures/textures_webapp/pokemon/duraludon/
    - assets/textures/textures_webapp/pokemon/dreepy/
    - assets/textures/textures_webapp/pokemon/drakloak/
    - assets/textures/textures_webapp/pokemon/dragapult/
    - assets/textures/textures_webapp/pokemon/zacian/
    - assets/textures/textures_webapp/pokemon/zamazenta/
    - assets/textures/textures_webapp/pokemon/eternatus/
    - assets/textures/textures_webapp/pokemon/kubfu/
    - assets/textures/textures_webapp/pokemon/urshifu/
    - assets/textures/textures_webapp/pokemon/zarude/
    - assets/textures/textures_webapp/pokemon/regieleki/
    - assets/textures/textures_webapp/pokemon/regidrago/
    - assets/textures/textures_webapp/pokemon/glastrier/
    - assets/textures/textures_webapp/pokemon/spectrier/
    - assets/textures/textures_webapp/pokemon/calyrex/
    - assets/textures/textures_webapp/pokemon/wyrdeer/
    - assets/textures/textures_webapp/pokemon/kleavor/
    - assets/textures/textures_webapp/pokemon/ursaluna/
    - assets/textures/textures_webapp/pokemon/basculegion/
    - assets/textures/textures_webapp/pokemon/sneasler/
    - assets/textures/textures_webapp/pokemon/overqwil/
    - assets/textures/textures_webapp/pokemon/enamorus/
    - assets/textures/textures_webapp/pokemon/sprigatito/
    - assets/textures/textures_webapp/pokemon/floragato/
    - assets/textures/textures_webapp/pokemon/meowscarada/
    - assets/textures/textures_webapp/pokemon/fuecoco/
    - assets/textures/textures_webapp/pokemon/crocalor/
    - assets/textures/textures_webapp/pokemon/skeledirge/
    - assets/textures/textures_webapp/pokemon/quaxly/
    - assets/textures/textures_webapp/pokemon/quaxwell/
    - assets/textures/textures_webapp/pokemon/quaquaval/
    - assets/textures/textures_webapp/pokemon/lechonk/
    - assets/textures/textures_webapp/pokemon/oinkologne/
    - assets/textures/textures_webapp/pokemon/tarountula/
    - assets/textures/textures_webapp/pokemon/spidops/
    - assets/textures/textures_webapp/pokemon/nymble/
    - assets/textures/textures_webapp/pokemon/lokix/
    - assets/textures/textures_webapp/pokemon/pawmi/
    - assets/textures/textures_webapp/pokemon/pawmo/
    - assets/textures/textures_webapp/pokemon/pawmot/
    - assets/textures/textures_webapp/pokemon/tandemaus/
    - assets/textures/textures_webapp/pokemon/maushold/
    - assets/textures/textures_webapp/pokemon/fidough/
    - assets/textures/textures_webapp/pokemon/dachsbun/
    - assets/textures/textures_webapp/pokemon/smoliv/
    - assets/textures/textures_webapp/pokemon/dolliv/
    - assets/textures/textures_webapp/pokemon/arboliva/
    - assets/textures/textures_webapp/pokemon/squawkabilly/
    - assets/textures/textures_webapp/pokemon/nacli/
    - assets/textures/textures_webapp/pokemon/naclstack/
    - assets/textures/textures_webapp/pokemon/garganacl/
    - assets/textures/textures_webapp/pokemon/charcadet/
    - assets/textures/textures_webapp/pokemon/armarouge/
    - assets/textures/textures_webapp/pokemon/ceruledge/
    - assets/textures/textures_webapp/pokemon/tadbulb/
    - assets/textures/textures_webapp/pokemon/bellibolt/
    - assets/textures/textures_webapp/pokemon/wattrel/
    - assets/textures/textures_webapp/pokemon/kilowattrel/
    - assets/textures/textures_webapp/pokemon/maschiff/
    - assets/textures/textures_webapp/pokemon/mabosstiff/
    - assets/textures/textures_webapp/pokemon/shroodle/
    - assets/textures/textures_webapp/pokemon/grafaiai/
    - assets/textures/textures_webapp/pokemon/bramblin/
    - assets/textures/textures_webapp/pokemon/brambleghast/
    - assets/textures/textures_webapp/pokemon/toedscool/
    - assets/textures/textures_webapp/pokemon/toedscruel/
    - assets/textures/textures_webapp/pokemon/klawf/
    - assets/textures/textures_webapp/pokemon/capsakid/
    - assets/textures/textures_webapp/pokemon/scovillain/
    - assets/textures/textures_webapp/pokemon/rellor/
    - assets/textures/textures_webapp/pokemon/rabsca/
    - assets/textures/textures_webapp/pokemon/flittle/
    - assets/textures/textures_webapp/pokemon/espathra/
    - assets/textures/textures_webapp/pokemon/tinkatink/
    - assets/textures/textures_webapp/pokemon/tinkatuff/
    - assets/textures/textures_webapp/pokemon/tinkaton/
    - assets/textures/textures_webapp/pokemon/wiglett/
    - assets/textures/textures_webapp/pokemon/wugtrio/
    - assets/textures/textures_webapp/pokemon/bombirdier/
    - assets/textures/textures_webapp/pokemon/finizen/
    - assets/textures/textures_webapp/pokemon/palafin/
    - assets/textures/textures_webapp/pokemon/varoom/
    - assets/textures/textures_webapp/pokemon/revavroom/
    - assets/textures/textures_webapp/pokemon/cyclizar/
    - assets/textures/textures_webapp/pokemon/orthworm/
    - assets/textures/textures_webapp/pokemon/glimmet/
    - assets/textures/textures_webapp/pokemon/glimmora/
    - assets/textures/textures_webapp/pokemon/greavard/
    - assets/textures/textures_webapp/pokemon/houndstone/
    - assets/textures/textures_webapp/pokemon/flamigo/
    - assets/textures/textures_webapp/pokemon/cetoddle/
    - assets/textures/textures_webapp/pokemon/cetitan/
    - assets/textures/textures_webapp/pokemon/veluza/
    - assets/textures/textures_webapp/pokemon/dondozo/
    - assets/textures/textures_webapp/pokemon/tatsugiri/
    - assets/textures/textures_webapp/pokemon/annihilape/
    - assets/textures/textures_webapp/pokemon/clodsire/
    - assets/textures/textures_webapp/pokemon/farigiraf/
    - assets/textures/textures_webapp/pokemon/dudunsparce/
    - assets/textures/textures_webapp/pokemon/kingambit/
    - assets/textures/textures_webapp/pokemon/great-tusk/
    - assets/textures/textures_webapp/pokemon/scream-tail/
    - assets/textures/textures_webapp/pokemon/brute-bonnet/
    - assets/textures/textures_webapp/pokemon/flutter-mane/
    - assets/textures/textures_webapp/pokemon/slither-wing/
    - assets/textures/textures_webapp/pokemon/sandy-shocks/
    - assets/textures/textures_webapp/pokemon/iron-treads/
    - assets/textures/textures_webapp/pokemon/iron-bundle/
    - assets/textures/textures_webapp/pokemon/iron-hands/
    - assets/textures/textures_webapp/pokemon/iron-jugulis/
    - assets/textures/textures_webapp/pokemon/iron-moth/
    - assets/textures/textures_webapp/pokemon/iron-thorns/
    - assets/textures/textures_webapp/pokemon/frigibax/
    - assets/textures/textures_webapp/pokemon/arctibax/
    - assets/textures/textures_webapp/pokemon/baxcalibur/
    - assets/textures/textures_webapp/pokemon/gimmighoul/
    - assets/textures/textures_webapp/pokemon/gholdengo/
    - assets/textures/textures_webapp/pokemon/wo-chien/
    - assets/textures/textures_webapp/pokemon/chien-pao/
    - assets/textures/textures_webapp/pokemon/ting-lu/
    - assets/textures/textures_webapp/pokemon/chi-yu/
    - assets/textures/textures_webapp/pokemon/roaring-moon/
    - assets/textures/textures_webapp/pokemon/iron-valiant/
    - assets/textures/textures_webapp/pokemon/koraidon/
    - assets/textures/textures_webapp/pokemon/miraidon/
    - assets/textures/textures_webapp/pokemon/walking-wake/
    - assets/textures/textures_webapp/pokemon/iron-leaves/
    - assets/textures/textures_webapp/pokemon/dipplin/
    - assets/textures/textures_webapp/pokemon/poltchageist/
    - assets/textures/textures_webapp/pokemon/sinistcha/
    - assets/textures/textures_webapp/pokemon/okidogi/
    - assets/textures/textures_webapp/pokemon/munkidori/
    - assets/textures/textures_webapp/pokemon/fezandipiti/
    - assets/textures/textures_webapp/pokemon/ogerpon/
    - assets/textures/textures_webapp/pokemon/archaludon/
    - assets/textures/textures_webapp/pokemon/hydrapple/
    - assets/textures/textures_webapp/pokemon/gouging-fire/
    - assets/textures/textures_webapp/pokemon/raging-bolt/
    - assets/textures/textures_webapp/pokemon/iron-boulder/
    - assets/textures/textures_webapp/pokemon/iron-crown/
    - assets/textures/textures_webapp/pokemon/terapagos/
    - assets/textures/textures_webapp/pokemon/pecharunt/
